name: github-actions-demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build ${{github.workspace}}/build --config Release
      - working-directory: ${{github.workspace}}/build
      - run: ctest -C Release
